[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'kassio/neoterm'
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite']
hook_add = '''
    let g:unite_enable_start_insert = 1
    let g:unite_enable_ignore_case = 1
    let g:unite_enable_smart_case = 1

    nmap <Space> [unite]
    nnoremap <silent> [unite]f :<C-u>Unite<Space>file_rec/async<CR>
    nnoremap <silent> [unite]g :<C-u>Unite<Space>file_rec/git<CR>
'''
hook_post_source = '''
    let s:unite_ignore_patterns='\.\(gif\|jpe\?g\|png\|webp\)$'
    call unite#custom#source('file_rec/async', 'ignore_pattern', s:unite_ignore_patterns)
    call unite#custom#source('file_rec/git', 'ignore_pattern', s:unite_ignore_patterns)
'''
if = "!has('nvim')"

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = ['Denite']
hook_add = '''
    nmap <Space> [unite]
    nnoremap <silent> [unite]f :<C-u>Denite<Space>file_rec<CR>
    nnoremap <silent> [unite]g :<C-u>Denite<Space>file_rec/git<CR>
'''
hook_post_source = '''
    call denite#custom#alias('source', 'file_rec/git', 'file_rec')
    call denite#custom#var('file_rec/git', 'command',
	      \ ['git', 'ls-files', '-co', '--exclude-standard'])
'''
if = "has('nvim')"

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_linters = {
    \    'html': ['htmlhint'],
    \    'php': ['php', 'phpcs'],
    \    'javascript': ['jshint']
    \}
    let g:ale_lint_on_text_changed = 'never'
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'thinca/vim-zenspace'
hook_add = '''
    let g:zenspace#default_mode = 'on'
    augroup vimrc-highlight
        autocmd!
        autocmd ColorScheme * highlight ZenSpace ctermbg=Red guibg=Red
    augroup END
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let NERDTreeShowHidden = 1
    command! Nt NERDTree
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['nerdtree', 'vim-fugitive']
hook_add = '''
    let g:lightline = {
        \ 'colorscheme': 'jellybeans',
        \ 'active': {
        \     'left': [
        \         ['mode', 'current_branch', 'paste'],
        \         [ 'modified', 'filename', 'readonly']
        \     ]
        \ },
        \ 'component': {
        \     'readonly': '%{&readonly?"[RO]":""}'
        \ },
        \ 'component_function': {
        \     'current_branch': 'CurrentBranch',
        \     'filename': 'FileName',
        \     'mode': 'MultiMode',
        \     'fileformat': 'FileFormat',
        \     'filetype': 'FileType',
        \     'fileencoding': 'FileEncoding'
        \ }
    \ }

    "-- lightline functions --"
    function! CurrentBranch()
        try
            if &ft !~? 'nerdtree' && exists('*fugitive#head') && strlen(fugitive#head())
                return "ト " . fugitive#head()
            endif
        catch
        endtry
        return ''
    endfunction

    function! FileName()
        if &ft !~? 'nerdtree'
            return expand('%:t')
        endif
        return ''
    endfunction

    function! MultiMode()
        let fname = expand('%:t')
        return fname =~ 'NERD_tree' ? 'NERDTree' : lightline#mode()
    endfunction

    function! FileFormat()
        return winwidth(0) > 70 ? &fileformat : ''
    endfunction

    function! FileType()
        return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
    endfunction

    function! FileEncoding()
        return winwidth(0) > 70 ? (&fenc !=# '' ? &fenc : &enc) : ''
    endfunction
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup=1
    let g:indent_guides_start_level=2
    let g:indent_guides_color_change_percent = 2
    let g:indent_guides_guide_size = 1
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
    let g:EditorConfig_core_mode = 'python_external'
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'vim-scripts/taglist.vim'
hook_add = '''
    let g:Tlist_Use_Right_Window = 1
    let g:Tlist_WinWidth = 40
'''

