[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite']
hook_add = '''
    let g:unite_enable_start_insert = 1
    let g:unite_enable_ignore_case = 1
    let g:unite_enable_smart_case = 1

    nmap <Space> [unite]
    nnoremap <silent> [unite]f :<C-u>Unite<Space>file_rec/async<CR>
    nnoremap <silent> [unite]g :<C-u>Unite<Space>file_rec/git<CR>
'''
hook_post_source = '''
    let s:unite_ignore_patterns='\.\(gif\|jpe\?g\|png\|webp\)$'
    call unite#custom#source('file_rec/async', 'ignore_pattern', s:unite_ignore_patterns)
    call unite#custom#source('file_rec/git', 'ignore_pattern', s:unite_ignore_patterns)
'''
if = "!has('nvim')"

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = ['Denite']
hook_add = '''
    nmap <Space> [unite]
    nnoremap <silent> [unite]f :<C-u>Denite<Space>file/rec<CR>
    nnoremap <silent> [unite]g :<C-u>Denite<Space>file/rec/git<CR>
'''
hook_post_source = '''
    call denite#custom#alias('source', 'file/rec/git', 'file/rec')
    call denite#custom#var('file/rec/git', 'command', ['git', 'ls-files', '-co', '--exclude-standard'])
    call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
    call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')

    autocmd FileType denite call s:denite_my_settings()
    function! s:denite_my_settings() abort
      nnoremap <silent><buffer><expr> <CR>
      \ denite#do_map('do_action')
      nnoremap <silent><buffer><expr> d
      \ denite#do_map('do_action', 'delete')
      nnoremap <silent><buffer><expr> p
      \ denite#do_map('do_action', 'preview')
      nnoremap <silent><buffer><expr> q
      \ denite#do_map('quit')
      nnoremap <silent><buffer><expr> i
      \ denite#do_map('open_filter_buffer')
      nnoremap <silent><buffer><expr> <Space>
      \ denite#do_map('toggle_select').'j'
    endfunction
'''
if = "has('nvim')"

[[plugins]]
repo = 'Shougo/neocomplete'
on_event = ['InsertEnter']
hook_add = '''
    let g:neocomplete#enable_at_startup = 1
'''
if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = ['InsertEnter']
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''
if = 'has("nvim") && has("python3")'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
on_event = ['InsertEnter']
build = './install.sh'

[[plugins]]
repo = 'lambdalisue/fern.vim'
on_event = ['CmdwinEnter']
hook_add = '''
    let g:fern#default_hidden = 1
    command! Nt Fern . -drawer
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_event = ['CmdwinEnter']
depends_on = ['fern.vim']

[[plugins]]
repo = 'glidenote/memolist.vim'
on_event = ['CmdwinEnter']
hook_add = '''
    let g:memolist_path = expand("~/Documents/Memos")
    let g:memolist_memo_suffix = "md"
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_event = ['InsertEnter']

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_add = '''
    let g:previm_open_cmd="open -a Safari"
    augroup PrevimSettings
        autocmd!
        autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
    augroup END
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_event = ['CmdwinEnter']

[[plugins]]
repo = 'KazuakiM/vim-sqlfix'
on_event = ['CmdwinEnter']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'html']

[[plugins]]
repo = 'mattn/vim-sqlfmt'
on_ft = ['sql']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
