[[plugins]]
repo = 'glidenote/memolist.vim'
on_event = ['CmdwinEnter']
hook_add = '''
    let g:memolist_path = expand("~/Documents/Memos")
    let g:memolist_memo_suffix = "md"
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_event = ['InsertEnter']

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_add = '''
    let g:previm_open_cmd="open -a Safari"
    augroup PrevimSettings
        autocmd!
        autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
    augroup END
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_event = ['CmdwinEnter']

[[plugins]]
repo = 'KazuakiM/vim-sqlfix'
on_event = ['CmdwinEnter']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'html']

[[plugins]]
repo = 'mattn/vim-sqlfmt'
on_ft = ['sql']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
